version: '3.9'
services:
  api:
    build: 
      context: .
      dockerfile: ./container/Dockerfile.local
    ports: 
      - "3000:3000"
    environment:
      - ./.env
    volumes:
      - type: bind
        source: ./api
        target: /src/app
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database:/database
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mysql-data: